In [2]:
import numpy as np
import pandas as pd

In [11]:
a = np.array([1,2,3])
b = np.array([[1,2,3]])
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9],[10,11,12]])
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(1, 3)
(4, 3)
[1 2 3] [[1 2 3]] [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [30]:
#创建连续等差数组
x1 = np.arange(1,11,2)
x2 = np.linspace(1,9,5)
print(x1)
print(x2)
print(x1==x2)

a = np.zeros((3,4)) # 数据全为0，3行4列
a = np.ones((3,4),dtype = np.int)   # 数据为1，3行4列

[1 3 5 7 9]
[1. 3. 5. 7. 9.]
[ True  True  True  True  True]
[[0.27198206 0.79450745 0.4791332  0.39157006]
 [0.80695498 0.3656961  0.28345068 0.22526591]]


In [31]:
#创建随机数组
a=np.random.random((2,4))
b=np.random.rand(2,4)   #[0, 1)随机分布
c=np.random.randn(2,4)  #标准正态分布
print(a)
print(b)
print(c)

[[0.8251106  0.49391338 0.83696276 0.88644793]
 [0.10314586 0.29424655 0.19745504 0.8927316 ]]
[[0.12911267 0.75240885 0.62091214 0.7905164 ]
 [0.81702885 0.63593961 0.42973464 0.60032489]]
[[-0.57973841 -0.11474264  0.07498353  0.23671971]
 [-0.03943466  0.78538687  0.46904523  0.07077839]]


In [28]:
#数组运算
x1 = np.arange(1,11,2)
x2 = np.array([2,3,4,7,8])
print(x1)
print(x2)
#加减乘除
print('add',np.add(x1, x2)) 
print(x1+x2)
print ('subtract',np.subtract(x1, x2))
print(x1-x2)
print ('multiply',np.multiply(x1, x2))
print(x1*x2)
print('divide',np.divide(x1, x2))
print(x1/2)
# n次方， 取余
print ('power',np.power(x1, x2))
print(x1**x2)
print ('remaninder',np.remainder(x1, x2))
print(x1%x2)

[1 3 5 7 9]
[2 3 4 7 8]
add [ 3  6  9 14 17]
[ 3  6  9 14 17]
subtract [-1  0  1  0  1]
[-1  0  1  0  1]
multiply [ 2  9 20 49 72]
[ 2  9 20 49 72]
divide [0.5   1.    1.25  1.    1.125]
[0.5 1.5 2.5 3.5 4.5]
power [       1       27      625   823543 43046721]
[       1       27      625   823543 43046721]
remaninder [1 0 1 0 1]
[1 0 1 0 1]


In [29]:
#矩阵运算
a=np.array([[1,1],[0,1]])
b=np.arange(4).reshape((2,2))
print(a)
print(b)
#矩阵运算
print(np.dot(a,b))


[[1 1]
 [0 1]]
[[0 1]
 [2 3]]
[[2 4]
 [2 3]]


In [23]:
#统计
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print (np.amin(a))
print (np.amin(a,axis=0))
print (np.amin(a,axis=1))
print (np.amax(a))
print (np.amax(a,0))
print (np.amax(a,1))

1
[1 2 3]
[1 4 7]
9
[7 8 9]
[3 6 9]


In [33]:
#h合并
A = np.array([1,1,1])
B = np.array([2,2,2])         
print(np.vstack((A,B)))  #  vertical stack   上下合并

C = np.hstack((A,B))     # horizontal stack  左右合并
print(C.shape)

[[1 1 1]
 [2 2 2]]
(6,)
